export const eventsList = [
  "IFC_RELATION_TREE_CHANGED",
  "CURRENT_VIEWER_CHANGED",
  "CURRENT_SELECTION_PROPERTIES_CHANGED",
  "MODEL_INDEXED",
  "PLANS_LIST_CHANGED",
  "SPACE_PLANNING_TREE_CHANGED",
  "SPACE_PLANNING_SUBSTITUTIONS_CHANGED",

  // Synoptiques
  "DATA_LOADED",
  "SYNOPTIQUES_LIST_CHANGED",
  "ACTIVE_FILTERS_CHANGED",
  "CATEGORY_LIST_CHANGED",
  "CATEGORY_MAPPING_CHANGED",
];
